#+Title:Writer Contract Number 1
#+Options: toc:nil author:nil
#+LaTeX_CLASS:article
#+LaTeX_CLASS_OPTIONS:[9pt]
#+LaTeX_HEADER:\usepackage[letterpaper, total={7.5in, 10.25in}]{geometry}
#+LaTeX_HEADER:\usepackage[parfill]{parskip} % add blank line between paragraphs and do not indent paragraphs.


This agreement starts August 1, 2021 (the "effective date") and will end
on October 1, 2021. The agreement is between _firstname lastname_
(Contractor) and _firstname lastname_ (Mentor). The Contractor must do
A-C each weekday while meeting conditions D-G. The Contractor may do
'windfall' writing outside of these writing blocks on the same or other
projects. The designated blocks of time in A-B do not need to be
adjacent. The Contractor is required to do the following writing tasks
per day.

A. Work on manuscript A1 for 90 minutes per day, M-F. Manuscript A1 is
the most important and urgent manuscript.

B. Work on one grant proposal for 90 minutes per day, M-F.

C. Generative writing for one book reaching a minimum of 1000 new words
by Friday of each week.

D. Qualifying text includes:

- Manuscripts, grant applications, books

- Editorial reviews of manuscripts and grant proposals

- Mind maps for planning manuscripts or grant applications

- Entries in writing logs

- Drafts of e-mails that are directly related to the project

- Heavily edited or newly generated scripts for making figures for the
  writing document

- Heavily edited or newly generated computer programs directly related
  to the project

- Entries to databases used in the research described in the paper.

- Entries in annotated bibliography

- Any other activity that advances the writing project

E. Confirm achievement of A and B by sending an email with "Done" on the
subject line to the Mentor by 11:59 PM. Done on Friday's means that the
book writing is finished.

F. The contractor may not do the following during the writing blocks and
will restart if any interruptions occur.

- Check e-mail

- Surf the web

- Listen to interview or news show videos on YouTube (music is okay if
  it is not distracting)

- Answer the phone

- Keep their office door open

- Accept visitors

G. During the writing blocks, the contractor may:

- Use the Pomodoro Technique

- Take bio breaks

- Do planning related to the writing project

- Retrieve and read literature

- Make figures

- Analyze data

- Write cover letters

- Submit manuscripts - edit text

- Work on bibliographies

- Track writing progress in Excel workbook

Contractor acknowledges to the Mentor that the Contractor agrees to
abide by this Agreement.

Contractor's signature: Date:

Mentor's signature: Date:
